// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdKOUJ4IQdQ02uwmk7elRIB1y6xf1rviA',
    appId: '1:292035189222:web:cc725f3642f2b91916de27',
    messagingSenderId: '292035189222',
    projectId: 'farm-connect-d1cb0',
    authDomain: 'farm-connect-d1cb0.firebaseapp.com',
    storageBucket: 'farm-connect-d1cb0.firebasestorage.app',
    measurementId: 'G-C9GKKMLKTK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHtupmVdHmneFCCvFAvVcz0Z3-ERylKQQ',
    appId: '1:292035189222:android:703efd998d5b1aef16de27',
    messagingSenderId: '292035189222',
    projectId: 'farm-connect-d1cb0',
    storageBucket: 'farm-connect-d1cb0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCry5xCRnNWi4x1J4F8mLOITV1xqwy6ygg',
    appId: '1:292035189222:ios:921477f2932dc14916de27',
    messagingSenderId: '292035189222',
    projectId: 'farm-connect-d1cb0',
    storageBucket: 'farm-connect-d1cb0.firebasestorage.app',
    iosBundleId: 'com.example.farmConnect',
  );
}